//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.TutorApplications = new HashSet<TutorApplication>();
        }
    
        public int RequirementId { get; set; }
        public int SubjectId { get; set; }
        public int GradeId { get; set; }
        public Nullable<int> GenderRequirement { get; set; }
        public Nullable<double> Tuition { get; set; }
        public Nullable<double> CostAdmin { get; set; }
        public string RequirementDetail { get; set; }
        public Nullable<int> LessionNumber { get; set; }
        public Nullable<int> RequirementStatus { get; set; }
        public Nullable<int> TutorNumber { get; set; }
        public Nullable<int> EndUserId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual EndUser EndUser { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorApplication> TutorApplications { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
