//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutor()
        {
            this.Detail_Subject_Grade = new HashSet<Detail_Subject_Grade>();
            this.TutorApplications = new HashSet<TutorApplication>();
        }
    
        public int TutorID { get; set; }
        public string TutorName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Avatar { get; set; }
        public string CMT { get; set; }
        public string TutorDetail { get; set; }
        public string Degree { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<double> AccountBalance { get; set; }
        public Nullable<int> TutorStatus { get; set; }
        public Nullable<int> JobId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detail_Subject_Grade> Detail_Subject_Grade { get; set; }
        public virtual Job Job { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorApplication> TutorApplications { get; set; }
    }
}
